### PR TITLE
moonbase: Fix restart advice getting stuck when changing option for the first time

### LINKED ISSUE #180: Strange error when saving spacepack settings
Happened when I enabled 'Add to global scope' in Spacepack

Image

Image

If I click reset and change more settings, the error is thrown again.

Restart fixes it... until I try to change that specific option again and the problem comes back.

### PR DESCRIPTION
**Pull request by TheKodeToad**
You can easily reproduce this by resetting the config file and enabling and disabling Add to global scope in Spacepack. The notice should disappear, but it doesn't.
Initially I was trying to fix #180 but it turns out that was already fixed and I was on the wrong branch :trollface: (I swear I read the docs I just kind of forgot)

### CODE REVIEW

**Comment by redstonekasi** [comment]
This was fixed in `develop` already if I remember correctly, please check that first.

**Comment by TheKodeToad** [comment]
Only that other error was fixed. And oops I also accidentally set the base branch to main lol

**Review by redstonekasi — CHANGES_REQUESTED** [review]
This is the not the proper place to fix this, `computeRestartAdvice` is for the reload notice at the top, not for the notice at the bottom, modifying config here is not desirable. Consider instead changing the logic in `showNotice` or making sure `modified` is correctly reset.

**Comment by TheKodeToad** [comment]
Uh I think this is a misunderstanding. The config is not being modified as a shallow copy is made.

Current Behaviour (latest commit of develop, pretty sure a release was just made so it's the same as main):

https://github.com/user-attachments/assets/a448783f-5b81-4d95-b2b2-916de82fa155

The notice at the top prompting the user to restart Discord stays there even though it should not

Fixed Behaviour (this PR):

https://github.com/user-attachments/assets/94d499a5-d0da-433d-9ec5-5ba998b135e2

File: packages/core-extensions/src/moonbase/webpackModules/stores.ts [hunk 1]
```diff
@@ -437,12 +437,19 @@ class MoonbaseSettingsStore extends Store<any> {
...
+      const newConfig = typeof newState === "boolean" ? {} : { ...newState?.config };
 
       const def = ext.manifest.settings;
       if (!def) continue;
 
+      for (const key in def) {
+        const defaultValue = def[key].default;
+
+        if (initConfig[key] == null) Object.defineProperty(initConfig, key, { value: defaultValue, enumerable: true });
+        if (newConfig[key] == null) Object.defineProperty(newConfig, key, { value: defaultValue, enumerable: true });
```
Comment (redstonekasi) [inline packages/core-extensions/src/moonbase/webpackModules/stores.ts:450]: Consider making these nullish coalescing assignments, that would be a bit more readable.

**Review by redstonekasi — CHANGES_REQUESTED** [review]
Ah I see, a similar issue exists for the "save config" notice so I assumed you were talking about that.

File: packages/core-extensions/src/moonbase/webpackModules/stores.ts (hunk 1 above)
Comment (redstonekasi) [reply packages/core-extensions/src/moonbase/webpackModules/stores.ts:450]: I see, that is indeed an issue for `__proto__` only, however nowhere is this currently handled and properly using objects with null prototypes everywhere would better fit in a separate PR.

**Review by redstonekasi — APPROVED** [review]
